source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'HaidoraStepProgressView_Example', :exclusive => true do
  pod "HaidoraStepProgressView", :path => "../"
end

target 'HaidoraStepProgressView_Tests', :exclusive => true do
  pod "HaidoraStepProgressView", :path => "../"

  
end
